apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: mortgage-channel
  namespace: mortgage-ch
spec:
  type: GitHub
  pathname: https://github.com/stolostron/application-samples.git
