apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    appname: rbdloop
  name: rbdloop-placement
  namespace: rbdloop-dashboard
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterReplicas: 1
  schedulerName: ramen
