apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: cloud-amazon-us-west-3
  namespace: provider
  annotations:
    apps.open-cluster-management.io/github-path: cloud-provider
    apps.open-cluster-management.io/github-branch: main
  labels:
    app: cloud
spec:
  channel: application-samples/gitops
  placement:
    placementRef:
      name: cloud-provider-a-us3
      kind: PlacementRule
  packageOverrides:
  - packageName: kustomization
    packageOverrides:
    - value:
        namespace: provider
        resources:
        - service.yaml
        - deployment-a-us3.yaml

