apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: bookinfo-mc1-placement
  namespace: istio-apps
  labels:
    app: bookinfo
spec:
  clusterReplicas: 1
  clusterSelector:
    matchLabels:
      name: mcsdemo1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: bookinfo-mc2-placement
  namespace: istio-apps
  labels:
    app: bookinfo
spec:
  clusterReplicas: 1
  clusterSelector:
    matchLabels:
      name: mcsdemo2
