apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: bookinfo-mc1-subscription
  namespace: istio-apps
  labels:
    app: bookinfo
  annotations:
    apps.open-cluster-management.io/github-path: istio-multicluster-servicemesh/bookinfo-mc1
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: istio-apps/istio-bookinfo-channel
  placement:
    placementRef:
      name: bookinfo-mc1-placement
      kind: PlacementRule
      group: apps.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: bookinfo-mc2-subscription
  namespace: istio-apps
  labels:
    app: bookinfo
  annotations:
    apps.open-cluster-management.io/github-path: istio-multicluster-servicemesh/bookinfo-mc2
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: istio-apps/istio-bookinfo-channel
  placement:
    placementRef:
      name: bookinfo-mc2-placement
      kind: PlacementRule
      group: apps.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: istio-ingressgateway-subscription
  namespace: istio-apps
  labels:
    app: bookinfo
  annotations:
    apps.open-cluster-management.io/github-path: istio-multicluster-servicemesh/istio-operator-gw
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: istio-apps/istio-bookinfo-channel
  placement:
    placementRef:
      name: bookinfo-mc1-placement
      kind: PlacementRule
      group: apps.open-cluster-management.io
