{
 "title": "Ramen Demo",
 "description": "Visualize the failover and failback of a test application",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Cluster 1 - 4K IOs During Grafana Interval",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(submit_time,$__interval,0),\n  count(id) AS \"id\"\nFROM ramendemo\nWHERE\n  $__timeFilter(submit_time) AND\n  isprimary = 1\nGROUP BY 1\nORDER BY $__timeGroup(submit_time,$__interval,0)"
    }
   ]
  },
  {
   "title": "Cluster 2 - 4K IOs During Grafana Interval",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(submit_time,$__interval,0),\n  count(id) AS \"id\"\nFROM ramendemo\nWHERE\n  $__timeFilter(submit_time) AND\n  isprimary = 0\nGROUP BY 1\nORDER BY $__timeGroup(submit_time,$__interval,0)"
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "bargauge",
   "description": "Track which cluster is active",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  submit_time AS \"time\",\n  cluster1,\n  cluster2\nFROM ramenfsid\nWHERE\n  $__timeFilter(submit_time)\nORDER BY submit_time"
    }
   ]
  },
  {
   "title": "Last Date Of Data From Cluster 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  submit_time AS \"time\",\n  prevdate AS metric,\n  cluster1\nFROM ramenfsid\nWHERE\n  $__timeFilter(submit_time) AND\n  prevdate != 0 AND\n  cluster1 = 1\nORDER BY submit_time"
    }
   ]
  },
  {
   "title": "Last Time Of Data From Cluster 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  submit_time AS \"time\",\n  prevtime AS metric,\n  cluster1\nFROM ramenfsid\nWHERE\n  $__timeFilter(submit_time) AND\n  prevdate != 0 AND\n  cluster1 = 1\nORDER BY submit_time"
    }
   ]
  },
  {
   "title": "Gap",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(submit_time,$__interval,0),\n  gap AS metric,\n  avg(cluster1) AS \"cluster1\"\nFROM ramenfsid\nWHERE\n  $__timeFilter(submit_time) AND\n  prevdate != 0 AND\n  cluster1 = 1\nGROUP BY 1,2\nORDER BY $__timeGroup(submit_time,$__interval,0)"
    }
   ]
  },
  {
   "title": "Last Date Of Data From Cluster 1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  submit_time AS \"time\",\n  prevdate AS metric,\n  cluster2\nFROM ramenfsid\nWHERE\n  $__timeFilter(submit_time) AND\n  prevdate != 0 AND\n  cluster2 = 1\nORDER BY submit_time"
    }
   ]
  },
  {
   "title": "Last Time Of Data From Cluster 1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  submit_time AS \"time\",\n  prevtime AS metric,\n  cluster2\nFROM ramenfsid\nWHERE\n  $__timeFilter(submit_time) AND\n  prevdate != 0 AND\n  cluster2 = 1\nORDER BY submit_time"
    }
   ]
  },
  {
   "title": "Gap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(submit_time,$__interval,0),\n  gap AS metric,\n  avg(cluster1) AS \"cluster1\"\nFROM ramenfsid\nWHERE\n  $__timeFilter(submit_time) AND\n  prevdate != 0 AND\n  cluster2 = 1\nGROUP BY 1,2\nORDER BY $__timeGroup(submit_time,$__interval,0)"
    }
   ]
  }
 ]
}