{
 "title": "Ramen Demo Application Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Preferred Cluster",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(submit_time,$__interval,0),\n  count(id) AS \"id\"\nFROM ramendemo\nWHERE\n  $__timeFilter(submit_time) AND\n  isprimary = 1\nGROUP BY 1\nORDER BY $__timeGroup(submit_time,$__interval,0)"
    }
   ]
  },
  {
   "title": "Failover Cluster",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(submit_time,$__interval,0),\n  count(id) AS \"id\"\nFROM ramendemo\nWHERE\n  $__timeFilter(submit_time) AND\n  isprimary = 0\nGROUP BY 1\nORDER BY $__timeGroup(submit_time,$__interval,0)"
    }
   ]
  },
  {
   "title": "Preferred Active",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  submit_time AS \"time\",\n  isprimary\nFROM ramendemo\nWHERE\n  $__timeFilter(submit_time)\nORDER BY submit_time"
    }
   ]
  },
  {
   "title": "Failover Active",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  submit_time AS \"time\",\n  issecondary\nFROM ramendemo\nWHERE\n  $__timeFilter(submit_time)\nORDER BY submit_time"
    }
   ]
  },
  {
   "title": "Last Gap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(submit_time,$__interval,0),\n  gap AS metric,\n  cluster1\nFROM ramenfsid\nWHERE\n  $__timeFilter(submit_time) AND\n  prevdate != 0 AND\n  cluster1 = 1\nGROUP BY 1,2\nORDER BY $__timeGroup(submit_time,$__interval,0)"
    }
   ]
  },
  {
   "title": "Last Gap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(submit_time,$__interval,0),\n  gap AS metric,\n  cluster2\nFROM ramenfsid\nWHERE\n  $__timeFilter(submit_time) AND\n  prevdate != 0 AND\n  cluster2 = 1\nGROUP BY 1,2\nORDER BY $__timeGroup(submit_time,$__interval,0)"
    }
   ]
  }
 ]
}