---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ramendemo-mysql-operatorgroup
  namespace: ramendemo-mysql
spec:
  serviceAccount:
    metadata:
      creationTimestamp: null
  targetNamespaces:
  - ramendemo-mysql
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
spec:
  channel: v4
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
