---
apiVersion: v1
kind: Service
metadata:
  name: ramendemo-mysql
  labels:
    app: ramendemo
spec:
  type: LoadBalancer
  ports:
    - port: 3306
  selector:
    app: ramendemo
    tier: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ramendemo-mysql-pv-claim
  labels:
    app: ramendemo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ramendemo-mysql
  labels:
    app: ramendemo
spec:
  selector:
    matchLabels:
      app: ramendemo
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ramendemo
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "redhat"
        - name: MYSQL_DATABASE
          value: "ramendemo"
        - name: MYSQL_USER
          value: "ramendemo"
        - name: MYSQL_PASSWORD
          value: "ramendemo"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: ramendemo-mysql-pv-claim
