apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-mc2
  namespace: istio-system
spec:
  profile: external
  components:
    base:
      enabled: true
    cni:
      enabled: true
      namespace: kube-system
      k8s:
        overlays:
          - kind: DaemonSet
            name: istio-cni-node
            patches:
              - path: spec.template.spec.containers[0].securityContext.privileged
                value: true
  values:
    global:
      configCluster: true
      meshID: mesh1
      multiCluster:
        clusterName: mcsdemo2
      network: network1
    pilot:
      configMap: true
    istiodRemote:
      injectionURL: https://istiod.istio-system.svc.clusterset.local:443/inject/:ENV:cluster=mcsdemo2:ENV:net=network1
    base:
      validationURL: https://istiod.istio-system.svc.clusterset.local:443/validate
    cni:
      cniBinDir: /var/lib/cni/bin
      cniConfDir: /etc/cni/multus/net.d
      chained: false
      cniConfFileName: "istio-cni.conf"
      excludeNamespaces:
       - istio-system
       - kube-system
      logLevel: info
    sidecarInjectorWebhook:
      injectedAnnotations:
        k8s.v1.cni.cncf.io/networks: istio-cni
