---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: pacman-sample
  labels:
    app: pacman-sample
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      usage: development
  #clusterReplicas: 1  #Apply to how many matched clusters, default is ALL
