---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: gitops
  namespace: application-samples
spec:
  type: GitHub
  pathname: https://github.com/open-cluster-management/application-samples.git
  secretRef:
    name: my-github-secret