apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-ingress
  namespace: istio-apps
spec:
  profile: empty
  components:
    ingressGateways:
    - name: ingressgateway
      namespace: istio-apps
      enabled: true
      label:
        istio: ingressgateway
  values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
