apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: istio-hub-subscription
  namespace: istio-system
  labels:
    app: istio-multicluster
  annotations:
    apps.open-cluster-management.io/github-path: istio-multicluster-servicemesh/istio-operator-hub
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: istio-system/istio-multicluster-channel
  placement:
    placementRef:
      name: istio-hub-placement
      kind: PlacementRule
      group: apps.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: istio-mc1-subscription
  namespace: istio-system
  labels:
    app: istio-multicluster
  annotations:
    apps.open-cluster-management.io/github-path: istio-multicluster-servicemesh/istio-operator-mc1
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: istio-system/istio-multicluster-channel
  placement:
    placementRef:
      name: istio-mc1-placement
      kind: PlacementRule
      group: apps.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: istio-mc2-subscription
  namespace: istio-system
  labels:
    app: istio-multicluster
  annotations:
    apps.open-cluster-management.io/github-path: istio-multicluster-servicemesh/istio-operator-mc2
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: istio-system/istio-multicluster-channel
  placement:
    placementRef:
      name: istio-mc2-placement
      kind: PlacementRule
      group: apps.open-cluster-management.io

