apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
  name: ingressgateway
spec:
  port:
    targetPort: http2
  to:
    kind: Service
    name: ingressgateway
    weight: 100
  wildcardPolicy: None
